id: PECCA79BA
initial_creation_type: input
source_metadata:
  title: Dharmak카rti Series
  language: bo
  description: 'Texts by and about the celebrated Indian philosopher Dharmak카rti (chos
    kyi grags pa):'
  volume:
    8f0634734f164712a51bbb67d85379cd:
      title: Guru S훮dhana of Glorious Dharmak카rti
      parent: Guru Yoga
created_at: '2022-03-01T02:14:55.812555'
last_modified_at: '2022-03-01T02:14:55.812557'
statistics:
  total_words: 629
  total_non_words: 63
quality:
  non_words_ratio: 0.1
